import "./ui/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavMenu from "./ui/components/NavMenu";
import { Providers } from "./ui/components/Providers";
import Navigation from "./ui/components/shared/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<Navigation />
					<main className="p-24">
						<NavMenu />
						{children}
					</main>
				</Providers>
			</body>
		</html>
	);
}
