import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const token = cookies().get("token");
	return (
		<html lang="en">
			<body className={inter.className}>
				<div style={{ background: "red" }}>Current cookie:{token?.value}</div> {children}
			</body>
		</html>
	);
}
