export const envVariables = {
	NEXT_PUBLIC_NEXTAUTH_URL: process.env.NEXT_PUBLIC_NEXTAUTH_URL || "",
	NEXT_PUBLIC_NEXTAUTH_SECRET: process.env.NEXT_PUBLIC_NEXTAUTH_SECRET || "",
	NEXT_PUBLIC_GITHUB_ID: process.env.NEXT_PUBLIC_GITHUB_ID || "",
	NEXT_PUBLIC_GITHUB_SECRET: process.env.NEXT_PUBLIC_GITHUB_SECRET || "",
	NEXT_PUBLIC_USER_KEY_LOCAL_STORAGE:
		process.env.NEXT_PUBLIC_USER_KEY_LOCAL_STORAGE || "",
	NEXT_PUBLIC_TOKEN_KEY_LOCAL_STORAGE:
		process.env.NEXT_PUBLIC_TOKEN_KEY_LOCAL_STORAGE || "",
	NEXT_PUBLIC_DB_USER: process.env.NEXT_PUBLIC_DB_USER || "",
	NEXT_PUBLIC_DB_PASSWORD: process.env.NEXT_PUBLIC_DB_PASSWORD || "",
	NEXT_PUBLIC_DB_NAME: process.env.NEXT_PUBLIC_DB_NAME || "",
	NEXT_PUBLIC_DB_HOST: process.env.NEXT_PUBLIC_DB_HOST || "",
	NEXT_PUBLIC_PORT:
		parseInt(process.env.NEXT_PUBLIC_PORT || "3000", 10) || 3000,
	NEXT_PUBLIC_JWT_SECRET: process.env.NEXT_PUBLIC_JWT_SECRET || "",
	NEXT_PUBLIC_ADMIN_ROLE: process.env.NEXT_PUBLIC_ADMIN_ROLE || "",
	NEXT_PUBLIC_PRODUCTION_URL: process.env.NEXT_PUBLIC_PRODUCTION_URL || "",
	NEXT_PUBLIC_GITHUB_CLIENT_SECRET:
		process.env.NEXT_PUBLIC_GITHUB_CLIENT_SECRET || "",
	NEXT_PUBLIC_GITHUB_CLIENT_ID: process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID || "",
	NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL || "",
	NEXT_PUBLIC_TYPE: process.env.NEXT_PUBLIC_TYPE || "",
	NEXT_PUBLIC_PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID || "",
	NEXT_PUBLIC_PRIVATE_KEY_ID: process.env.NEXT_PUBLIC_PRIVATE_KEY_ID || "",
	NEXT_PUBLIC_PRIVATE_KEY: process.env.NEXT_PUBLIC_PRIVATE_KEY || "",
};
